require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BattingStatisticsController do

  # This should return the minimal set of attributes required to create a valid
  # BattingStatistic. As you add validations to BattingStatistic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "player_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BattingStatisticsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all batting_statistics as @batting_statistics" do
      batting_statistic = BattingStatistic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:batting_statistics).should eq([batting_statistic])
    end
  end

  describe "GET show" do
    it "assigns the requested batting_statistic as @batting_statistic" do
      batting_statistic = BattingStatistic.create! valid_attributes
      get :show, {:id => batting_statistic.to_param}, valid_session
      assigns(:batting_statistic).should eq(batting_statistic)
    end
  end

  describe "GET new" do
    it "assigns a new batting_statistic as @batting_statistic" do
      get :new, {}, valid_session
      assigns(:batting_statistic).should be_a_new(BattingStatistic)
    end
  end

  describe "GET edit" do
    it "assigns the requested batting_statistic as @batting_statistic" do
      batting_statistic = BattingStatistic.create! valid_attributes
      get :edit, {:id => batting_statistic.to_param}, valid_session
      assigns(:batting_statistic).should eq(batting_statistic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BattingStatistic" do
        expect {
          post :create, {:batting_statistic => valid_attributes}, valid_session
        }.to change(BattingStatistic, :count).by(1)
      end

      it "assigns a newly created batting_statistic as @batting_statistic" do
        post :create, {:batting_statistic => valid_attributes}, valid_session
        assigns(:batting_statistic).should be_a(BattingStatistic)
        assigns(:batting_statistic).should be_persisted
      end

      it "redirects to the created batting_statistic" do
        post :create, {:batting_statistic => valid_attributes}, valid_session
        response.should redirect_to(BattingStatistic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved batting_statistic as @batting_statistic" do
        # Trigger the behavior that occurs when invalid params are submitted
        BattingStatistic.any_instance.stub(:save).and_return(false)
        post :create, {:batting_statistic => { "player_id" => "invalid value" }}, valid_session
        assigns(:batting_statistic).should be_a_new(BattingStatistic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BattingStatistic.any_instance.stub(:save).and_return(false)
        post :create, {:batting_statistic => { "player_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested batting_statistic" do
        batting_statistic = BattingStatistic.create! valid_attributes
        # Assuming there are no other batting_statistics in the database, this
        # specifies that the BattingStatistic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BattingStatistic.any_instance.should_receive(:update).with({ "player_id" => "" })
        put :update, {:id => batting_statistic.to_param, :batting_statistic => { "player_id" => "" }}, valid_session
      end

      it "assigns the requested batting_statistic as @batting_statistic" do
        batting_statistic = BattingStatistic.create! valid_attributes
        put :update, {:id => batting_statistic.to_param, :batting_statistic => valid_attributes}, valid_session
        assigns(:batting_statistic).should eq(batting_statistic)
      end

      it "redirects to the batting_statistic" do
        batting_statistic = BattingStatistic.create! valid_attributes
        put :update, {:id => batting_statistic.to_param, :batting_statistic => valid_attributes}, valid_session
        response.should redirect_to(batting_statistic)
      end
    end

    describe "with invalid params" do
      it "assigns the batting_statistic as @batting_statistic" do
        batting_statistic = BattingStatistic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BattingStatistic.any_instance.stub(:save).and_return(false)
        put :update, {:id => batting_statistic.to_param, :batting_statistic => { "player_id" => "invalid value" }}, valid_session
        assigns(:batting_statistic).should eq(batting_statistic)
      end

      it "re-renders the 'edit' template" do
        batting_statistic = BattingStatistic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BattingStatistic.any_instance.stub(:save).and_return(false)
        put :update, {:id => batting_statistic.to_param, :batting_statistic => { "player_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested batting_statistic" do
      batting_statistic = BattingStatistic.create! valid_attributes
      expect {
        delete :destroy, {:id => batting_statistic.to_param}, valid_session
      }.to change(BattingStatistic, :count).by(-1)
    end

    it "redirects to the batting_statistics list" do
      batting_statistic = BattingStatistic.create! valid_attributes
      delete :destroy, {:id => batting_statistic.to_param}, valid_session
      response.should redirect_to(batting_statistics_url)
    end
  end

end
