require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FantasyPointsController do

  # This should return the minimal set of attributes required to create a valid
  # FantasyPoint. As you add validations to FantasyPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "home_run" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FantasyPointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fantasy_points as @fantasy_points" do
      fantasy_point = FantasyPoint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fantasy_points).should eq([fantasy_point])
    end
  end

  describe "GET show" do
    it "assigns the requested fantasy_point as @fantasy_point" do
      fantasy_point = FantasyPoint.create! valid_attributes
      get :show, {:id => fantasy_point.to_param}, valid_session
      assigns(:fantasy_point).should eq(fantasy_point)
    end
  end

  describe "GET new" do
    it "assigns a new fantasy_point as @fantasy_point" do
      get :new, {}, valid_session
      assigns(:fantasy_point).should be_a_new(FantasyPoint)
    end
  end

  describe "GET edit" do
    it "assigns the requested fantasy_point as @fantasy_point" do
      fantasy_point = FantasyPoint.create! valid_attributes
      get :edit, {:id => fantasy_point.to_param}, valid_session
      assigns(:fantasy_point).should eq(fantasy_point)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FantasyPoint" do
        expect {
          post :create, {:fantasy_point => valid_attributes}, valid_session
        }.to change(FantasyPoint, :count).by(1)
      end

      it "assigns a newly created fantasy_point as @fantasy_point" do
        post :create, {:fantasy_point => valid_attributes}, valid_session
        assigns(:fantasy_point).should be_a(FantasyPoint)
        assigns(:fantasy_point).should be_persisted
      end

      it "redirects to the created fantasy_point" do
        post :create, {:fantasy_point => valid_attributes}, valid_session
        response.should redirect_to(FantasyPoint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fantasy_point as @fantasy_point" do
        # Trigger the behavior that occurs when invalid params are submitted
        FantasyPoint.any_instance.stub(:save).and_return(false)
        post :create, {:fantasy_point => { "home_run" => "invalid value" }}, valid_session
        assigns(:fantasy_point).should be_a_new(FantasyPoint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FantasyPoint.any_instance.stub(:save).and_return(false)
        post :create, {:fantasy_point => { "home_run" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fantasy_point" do
        fantasy_point = FantasyPoint.create! valid_attributes
        # Assuming there are no other fantasy_points in the database, this
        # specifies that the FantasyPoint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FantasyPoint.any_instance.should_receive(:update).with({ "home_run" => "" })
        put :update, {:id => fantasy_point.to_param, :fantasy_point => { "home_run" => "" }}, valid_session
      end

      it "assigns the requested fantasy_point as @fantasy_point" do
        fantasy_point = FantasyPoint.create! valid_attributes
        put :update, {:id => fantasy_point.to_param, :fantasy_point => valid_attributes}, valid_session
        assigns(:fantasy_point).should eq(fantasy_point)
      end

      it "redirects to the fantasy_point" do
        fantasy_point = FantasyPoint.create! valid_attributes
        put :update, {:id => fantasy_point.to_param, :fantasy_point => valid_attributes}, valid_session
        response.should redirect_to(fantasy_point)
      end
    end

    describe "with invalid params" do
      it "assigns the fantasy_point as @fantasy_point" do
        fantasy_point = FantasyPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FantasyPoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => fantasy_point.to_param, :fantasy_point => { "home_run" => "invalid value" }}, valid_session
        assigns(:fantasy_point).should eq(fantasy_point)
      end

      it "re-renders the 'edit' template" do
        fantasy_point = FantasyPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FantasyPoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => fantasy_point.to_param, :fantasy_point => { "home_run" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fantasy_point" do
      fantasy_point = FantasyPoint.create! valid_attributes
      expect {
        delete :destroy, {:id => fantasy_point.to_param}, valid_session
      }.to change(FantasyPoint, :count).by(-1)
    end

    it "redirects to the fantasy_points list" do
      fantasy_point = FantasyPoint.create! valid_attributes
      delete :destroy, {:id => fantasy_point.to_param}, valid_session
      response.should redirect_to(fantasy_points_url)
    end
  end

end
